### ISSUE TITLE
textembedding-gecko@001

### ISSUE THREAD

**Issue by kaisugi** [oshizo/JapaneseEmbeddingEval#4]
[textembedding-gecko@001](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text-embeddings) は Google Cloud の Vertex AI に内包されている埋め込みモデルです。
text-embedding-ada-002 との対比でどのくらい性能がいいのか気になるので Isuue 化しておきます！

**Comment by oshizo** [comment]
textembedding-gecko-multilingual@001がこのpull requestで評価されました。
https://github.com/oshizo/JapaneseEmbeddingEval/pull/9
